global:
  scrape_interval: 15s

scrape_configs:
  - job_name: keycloak
    static_configs:
      - targets: ["keycloak:9000"]
    metrics_path: /metrics

  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
    metrics_path: /metrics